// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxIDS5oKv917C8q1dUdepaeAlN-Gl3NTo',
    appId: '1:412624561473:web:ecc142e64a4642647dadc0',
    messagingSenderId: '412624561473',
    projectId: 'oamk-kiertotalous',
    authDomain: 'oamk-kiertotalous.firebaseapp.com',
    databaseURL: 'https://oamk-kiertotalous-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'oamk-kiertotalous.appspot.com',
    measurementId: 'G-89GEZEN5Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCxkCddeF26XHmN9ns9-lZu65P6WmWa2A',
    appId: '1:412624561473:android:91cf173f1e2ead077dadc0',
    messagingSenderId: '412624561473',
    projectId: 'oamk-kiertotalous',
    databaseURL: 'https://oamk-kiertotalous-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'oamk-kiertotalous.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKGJMKHJBeg2I3kD6hmnft5p20lMxofrg',
    appId: '1:412624561473:ios:3b53e1c56e43c0437dadc0',
    messagingSenderId: '412624561473',
    projectId: 'oamk-kiertotalous',
    databaseURL: 'https://oamk-kiertotalous-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'oamk-kiertotalous.appspot.com',
    androidClientId: '412624561473-0imp307qp18sskrco9iq9ebt3oosgdkk.apps.googleusercontent.com',
    iosClientId: '412624561473-3gc3n7esspckkrs1tc6kuarnkpm43dr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.oivaAppFlutter',
  );
}
